server:
  port: 8888

logging:
  level:
    org.springframework: INFO
    com.onestop: debug
  pattern:
    console: '%date{"yyyy/MM/dd HH:mm:ss,SSS", UTC} [%p] [%t] %M\(%F:%L\) - %msg%n'
spring:
  data:
    redis:
      database: 0
      # Redis服务器地址
      host: xxxx
      # Redis服务器连接端口
      port: 6379
      # Redis6.0服务器连接用户名
      username:
      # Redis服务器连接密码（默认为空）
      password:
      lettuce:
        shutdown-timeout: 2000