server:
  port: 8888

logging:
  level:
    org.springframework: INFO
    com.onestop: debug
spring:
  redis:
    database: 3
    # Redis服务器地址
    host: xxxx
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000
    lettuce:
      shutdown-timeout: 2000
os:
  # 服务端api地址
  service:
    apiBaseUrl: http://localhost
  redis:
    # 开启redis工具类、不配置spring.redis为采用默认值，也可自定义配置
    enabled: true