server:
  port: 8888

logging:
  level:
    org.springframework: INFO
    com.onestop: debug
spring:
  data:
    redis:
      database: 1
      # Redis服务器地址
      host: xxxx
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password:
      # 连接超时时间（毫秒）
      timeout: 5000
      lettuce:
        shutdown-timeout: 2000