reply:
  config:
    name: reply-config
os:
  wxmp:
    reply:
      configs:
        #关键字
        - keyword: subscribe
          #文本回复内容
          replyText: 感谢您的关注！
        #关键字
#        - keyword: subscribe
#          replyType: news
#          article:
#            title: 感谢您的关注
#            description: 今天医疗简介
#            picUrl: https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic.soutu123.com%2Felement_origin_min_pic%2F16%2F07%2F07%2F15577e01396c9ef.jpg%21%2Ffw%2F700%2Fquality%2F90%2Funsharp%2Ftrue%2Fcompress%2Ftrue&refer=http%3A%2F%2Fpic.soutu123.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1671353128&t=783cdcad2235fe9b7f13470f122aeb48
#            url: https://www.163.com