server:
  port: 80

logging:
  level:
    org.springframework: INFO
    me.chanjar.weixin: INFO
    com.onestop: DEBUG

os:
  wxmp:
    appid:  #微信appid
    secret:  #微信Secret
    token:  #默认值
    aesKey:  #默认值
    uiPath:
    menu:
      enabled: true
    # 开启关键字回复配置
    reply:
      enabled: true
