server:
  port: 80

logging:
  level:
    org.springframework: INFO
    me.chanjar.weixin: INFO
    com.onestop: DEBUG
  pattern:
    console: '%date{"yyyy/MM/dd HH:mm:ss,SSS", UTC} [%p] [%t] %M\(%F:%L\) - %msg%n'
os:
  # api路由前缀
  service:
    domain: http://wx.xxxx.com
    apiPath: wxmp/api
    # api完整路径
    apiFullPath: ${os.service.domain}/${os.service.apiPath}
    # 前端路径
    uiFullPath: ${os.service.domain}/wxui
  wxmp:
    appid:  #微信appid
    secret:  #微信Secret
    token: onestop
    aesKey:  #默认值
    txtPath: d:/txt/
    menu:
      enabled: true
    reply:
      enabled: true
    subscribe:
      enabled: true
