menu:
  config:
    name: menu-config
os:
  wxmp:
    menu:
      configs:
        #菜单ID
        - id: 1
          #父级菜单ID
          parentId: 0
          #菜单的响应动作类型，view表示网页类型，click表示点击类型，miniprogram表示小程序类型
          menuType: view
          #菜单标题
          menuName: 会员申请
          #菜单key
          menuKey: b1
          #view、miniprogram类型必须
          url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${os.wxmp.appid}&redirect_uri=${os.service.apiFullPath}/goto/getAccessToken&response_type=code&scope=snsapi_userinfo&state=index&connect_redirect=1#wechat_redirect
          #小程序的appid
#          appid:
          #小程序的页面路径
#          pagepath:
          #菜单级别：1：一级、2：二级
          menuLevel: 1
#        #菜单ID
#        - id: 2
#          #父级菜单ID
#          parentId: 0
#          #菜单的响应动作类型，view表示网页类型，click表示点击类型，miniprogram表示小程序类型
#          menuType: view
#          #菜单标题
#          menuName: 自助查询
#          #菜单key
#          menuKey: b2
#          #view、miniprogram类型必须
#          url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx930d31e7062a95ea&redirect_uri=http://365.nat100.top/wxmp/api/goto/getAccessToken&response_type=code&scope=snsapi_userinfo&state=list&connect_redirect=1#wechat_redirect
#          #小程序的appid
##          appid:
#          #小程序的页面路径
##          pagepath:
#          #菜单级别：1：一级、2：二级
#          menuLevel: 1
#        #菜单ID
#        - id: 3
#          #父级菜单ID
#          parentId: 0
#          #菜单的响应动作类型，view表示网页类型，click表示点击类型，miniprogram表示小程序类型
#          menuType: view
#          #菜单标题
#          menuName: 个人中心
#          #菜单key
#          menuKey: b3
#          #view、miniprogram类型必须
#          url: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx930d31e7062a95ea&redirect_uri=http://365.nat100.top/wxmp/api/goto/getAccessToken&response_type=code&scope=snsapi_userinfo&state=userRegister&connect_redirect=1#wechat_redirect
#          #小程序的appid
#          #          appid:
#          #小程序的页面路径
#          #          pagepath:
#          #菜单级别：1：一级、2：二级
#          menuLevel: 1