server:
  port: 80

logging:
  level:
    org.springframework: info
    cn.binarywang: info
    com.onestop: debug
  pattern:
    console: '%date{"yyyy/MM/dd HH:mm:ss,SSS", UTC} [%p] [%t] %M\(%F:%L\) - %msg%n'
os:
  wxmini:
    #小程序
    appid: #微信小程序的appid
    secret: #微信小程序的Secret
    token:  #默认值
    aesKey:  #默认值
    msgDataFormat: JSON #默认JSON
    #上传路径
    uploadPath: e:/ #/home/wxmini/upload/
    #订阅消息模板
    subscribe:
      # 开启订阅消息配置
      enabled: true
  oss:
    # AccessKey ID
    accessKeyId: xxxx
    # AccessKey Secret
    accessKeySecret: xxxx
    # endpoint
    endpoint: oss-cn-beijing.aliyuncs.com
    # bucketName
    bucketName: xxxx
