server:
  port: 80

logging:
  level:
    org.springframework: info
    cn.binarywang: info
    com.onestop: debug
# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.rds.aliyuncs.com:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password:

mybatis-plus:
  global-config:
    db-config:
      #逻辑删除配置（下面3个配置）
      logic-delete-field: deleted

os:
  wxmini:
    #小程序
    appid: #微信小程序的appid
    secret: #微信小程序的Secret
    token:  #默认值
    aesKey:  #默认值
    msgDataFormat: JSON #默认JSON
    #上传路径
    uploadPath: e:/ #/home/wxmini/upload/
    #订阅消息模板
    subscribe:
      # 开启订阅消息配置
      enabled: true
  oss:
    # AccessKey ID
    accessKeyId: xxxx
    # AccessKey Secret
    accessKeySecret: xxxx
    # endpoint
    endpoint: oss-cn-beijing.aliyuncs.com
    # bucketName
    bucketName: xxxx
