server:
  port: 80

logging:
  level:
    org.springframework: INFO
    com.onestop: INFO
  pattern:
    console: '%date{"yyyy/MM/dd HH:mm:ss,SSS", UTC} [%p] [%t] %M\(%F:%L\) - %msg%n'
os:
  aes:
    # 私钥
    secret: 0123456789ABCDEF
  token:
    # 私钥
    secret: 0123456789ABCDEF