#基础镜像：anapsix，标签用8u202
FROM anapsix/alpine-java:8_server-jre_unlimited
#当前镜像的维护者和联系方式
MAINTAINER Clark changch@neusoft.com
#将打包好的spring程序拷贝到容器中的指定位置
ADD jar/wxmp.jar /app/
#设置时区
#RUN /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
#容器启动后需要执行的命令
CMD ["java", "-Xmx512m", "-jar", "-Dspring.profiles.active=prod", "/app/wxmp.jar"]