server:
  port: 8011
nacos:
  config:
    server-addr: 127.0.0.1:8848

spring:
  application:
    name: @project.artifactId@
  cloud:
    nacos:
      config:
        server-addr: ${nacos.config.server-addr}
        file-extension: yml
        dataId: ${spring.application.name}.yml
      discovery:
        server-addr: ${nacos.config.server-addr}
